project:
  artifactId: 'rps-game'
  appName: '@appName@'
  name: 'rps-game'
  version: '0.0.1-SNAPSHOT'
  description: 'Rock Paper Scissors game'
  groupId: 'com.rps'
  
spring:
  application:
    name: ${project.artifactId}
  thymeleaf :
    cache : false

server:
  port: 8080
  error:
    include-stacktrace : always

logging:
  level:
    org:
      springframework: INFO